export const LOAD_USER_DATA = 'LOAD_USER_DATA';
export const SEND_AUTH_REQUEST = 'SEND_AUTH_REQUEST';
export const LOG_OUT = 'LOG_OUT';

export const HIDE_LOADING_BAR = 'HIDE_LOADING_BAR';
export const SHOW_LOADING_BAR = 'SHOW_LOADING_BAR';

export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';

export const TRIGGER_NAV_DRAWER = 'TRIGGER_NAV_DRAWER';

export const LOAD_PROJECTS = 'LOAD_PROJECTS';
export const FETCH_PROJECTS = 'FETCH_PROJECTS';