export const LOAD_USER_DATA = 'LOAD_USER_DATA';
export const SEND_AUTH_REQUEST = 'SEND_AUTH_REQUEST';
export const LOG_OUT = 'LOG_OUT';

export const HIDE_LOADING_BAR = 'HIDE_LOADING_BAR';
export const SHOW_LOADING_BAR = 'SHOW_LOADING_BAR';

export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';

export const TRIGGER_NAV_DRAWER = 'TRIGGER_NAV_DRAWER';

export const LOAD_PROJECTS = 'LOAD_PROJECTS';
export const FETCH_PROJECTS = 'FETCH_PROJECTS';
export const VALIDATE_PROJECT = 'VALIDATE_PROJECT';
export const CREATE_OR_UPDATE_PROJECT = 'CREATE_OR_UPDATE_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const REMOVE_PROJECT = 'REMOVE_PROJECT';
export const LOAD_USERS = 'LOAD_USERS';
export const FETCH_USERS = 'FETCH_USERS';
export const VALODATE_LOGIN = 'VALODATE_LOGIN';
export const CREATE_USER = 'CREATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const REMOVE_USER = 'REMOVE_USER';

export const CREATE_NEW_PROJECT = 'CREATE_NEW_PROJECT';
export const EDIT_PROJECT = 'EDIT_PROJECT';
export const FETCH_PROJECT_FOR_EDIT = 'FETCH_PROJECT_FOR_EDIT';

export const SHOW_CONFIRMATION = 'SHOW_CONFIRMATION';
export const CLOSE_CONFIRMATION = 'CLOSE_CONFIRMATION';